### ISSUE TITLE
Microsoft Edge: JSON.parse Error: Unexpected input at position

### ISSUE THREAD

**Issue by mrdoob** [puckey/dance-tonite#11]
There seems to be something wrong with the animation jsons.

![dance](https://user-images.githubusercontent.com/97088/29783346-ef156c5e-8bd4-11e7-9808-7eb48cf6332c.PNG)

![dance2](https://user-images.githubusercontent.com/97088/29783354-f55077ee-8bd4-11e7-95d6-198d9420409a.PNG)

**Comment by customlogic** [comment]
Hmm.. it's working on Edge for me. I haven't done the "Creators update" yet, though. What version 
of Edge are you using?

**Comment by mrdoob** [comment]
The problem seems to be gone in the latest Edge (41.16273.1000.0).

**Comment by mrdoob** [comment]
The music stops when entering VR though.
