### ISSUE TITLE
Add "Create GIF" to the gallery?

### ISSUE THREAD

**Issue by customlogic** [puckey/dance-tonite#13]
Hey @puckey, what would it take to add the "create a gif" process to the gallery page? It'd be nice for people to get GIF's whenever they want. 

I tried to figure it out myself, but I don't know preact well enough. It seems like the createGif component is tried in to the "Playback Flow", but I'm not sure how to decouple them.

**Comment by puckey** [comment]
I implemented this in the [gallery-gif](https://github.com/puckey/dance-tonite/tree/gallery-gif) branch. It adds a 'Create GIF' button to the bottom right on the gallery page. (hidden on mobile)

Preview: https://gallery-gif--dance-tonite.netlify.com/

Feel free to merge after testing!

**Comment by customlogic** [comment]
Great, thank you! I tested on all major Mac & PC browsers, all looks good. I've merged and deployed live.
