### ISSUE TITLE
Performance choppy after submitting performance

### ISSUE THREAD

**Issue by customlogic** [puckey/dance-tonite#14]
This was reported by the QA team. but we weren't about to reproduce at the office:

During testing the Performance of the Rift and Vive was smooth however after they record a performance and submit it then the frame rate drops when viewing the preview.
This continues when they go back to the home page and views the full experience, however its resolved if they refresh the page and enter VR again.
Device:
Oculus Rift - Chromium
HTC Vive - Chromium

User's have also noted the problem. You can see it in action during this video of a user creating performances and submitting them you can see the problem at 14:17 and again at 24:30
https://www.youtube.com/watch?v=qQTBvc7rJOE&feature=youtu.be

**Comment by mflux** [comment]
Is this re-opened? It was just assigned again.

**Comment by customlogic** [comment]
Yeah, have a look at the video that was sent to us by a user (in description above). You can see it pretty dramatically

**Comment by customlogic** [comment]
Hey @puckey, @mflux and I haven't been able to reproduce it, but it's clearly a problem that's happening for people (see video). What if we make the "Watch yourself in the Full Experience" link and actual link that reloads the page, rather than just an internal route? This just clear out whatever the problem is, and shouldn't affect flow in any way that I can see.

**Comment by puckey** [comment]
Yes, that makes a lot of sense. I should be able to find a moment to implement this.

**Comment by puckey** [comment]
I implemented this in the [redirect-full-experience](https://github.com/puckey/dance-tonite/tree/redirect-full-experience) branch. It reloads the page by setting window.location.

Preview: https://redirect-full-experience--dance-tonite.netlify.com/

Feel free to merge after testing!

**Comment by customlogic** [comment]
Thanks! Tested and seems fine. I've pushed the change live
