### ISSUE TITLE
Timing of mega-grid performances a bit off?

### ISSUE THREAD

**Issue by customlogic** [puckey/dance-tonite#17]
I think the timing of the performances happening in the megagrid are slightly off. You notice this when you're flying through, because you'll "fly through" the performance much earlier than the performance was designed for.

for example, a group of dancers in front of the hole who spread out to make way for the ball. If this performance ends up in the mega grid, you may fly through the dancers because the timing is out of whack

**Comment by puckey** [comment]
This one totally passed me by – fixed now. Could you deploy the site with this new change?

**Comment by customlogic** [comment]
Thanks for the fix! I've deployed to the live site
