### ISSUE TITLE
Doesn't work correctly in latest Chrome

### ISSUE THREAD

**Issue by customlogic** [puckey/dance-tonite#23]
The video never starts because Chrome expects a user gesture before it'll play audio. I guess we can just turn on the "press play to start" button like we did for Safari

**Comment by customlogic** [comment]
Yes, I think that’s probably best

**Comment by customlogic** [comment]
Also, I noticed the csm doesn’t seem to be working properly since I
upgraded chrome. I think it requires https to work correctly. Are you able
to add an ssl cert to the cms on puckey.studio?

**Comment by customlogic** [comment]
Okay, the "press play to start" button now shows for all browsers. The site is working again in latest Chrome

**Comment by puckey** [comment]
Thanks Jeff!

**Comment by puckey** [comment]
I will look into turning the CMS into https this weekend (in the middle of giving a workshop this week)

**Comment by customlogic** [comment]
The CMS is working fine now. It turned out to be a problem with the Firebase functions which I've now fixed. So all good!
