### ISSUE TITLE
TLS certificate expired

### ISSUE THREAD

**Issue by cvan** [puckey/dance-tonite#26]
It looks like the certificate expired today, November 15, 2018. https://tls-observatory.services.mozilla.com/static/certsplainer.html?id=186787787

![image](https://user-images.githubusercontent.com/203725/48590683-51b13680-e8f5-11e8-9a28-92b48f32a6e8.png)

**Comment by Firepal** [comment]
It has once again expired. welllllp.

**Comment by puckey** [comment]
Thanks for the heads up! Looks like it has been fixed in the meantime
